schema_version = "1.0.0"
id = "module_installer"
version = "0.3.0"
name = "module installer"
tagline = "Install third party modules using python wheels"
maintainer = "haseebahmad295 <quicktiptech@gmail.com>"
type = "add-on"
website = "https://github.com/haseebahmed295/blender-Free-Gpt"
tags = [ "Development",]
wheels = []
blender_version_min = "4.2.0"
license = [ "SPDX:GPL-3.0-or-later",]

[permissions]
network = "To download wheel files"

[build]
paths_exclude_pattern = [ "/.git/", "__pycache__/",]
